base: 'http://physio2021.ddev.site/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de
    direction: ltr
    flag: de
    websiteTitle: 'Physiotherapie im Mediapark'
rootPageId: 1
websiteTitle: 'Physiotherapie im Mediapark'
